# Generated by Django 4.2.7 on 2023-12-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcartitem',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
