# Generated by Django 5.0 on 2023-12-09 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('artist', models.CharField(max_length=255, verbose_name='Artista')),
                ('record_label', models.CharField(max_length=255, verbose_name='Gravadora')),
                ('release_date', models.DateField(verbose_name='Data de lançamento')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('img', models.ImageField(upload_to='frontend/static/upload/musics/', verbose_name='Imagem')),
                ('slug', models.SlugField(unique=True)),
                ('format', models.CharField(choices=[('CD', 'CD'), ('DVD', 'DVD'), ('Disco de Vinil', 'Disco de Vinil'), ('Blu-ray', 'Blu-ray')], max_length=14, verbose_name='Formato')),
                ('categories', models.ManyToManyField(to='musics.category', verbose_name='Categorias')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título da Faixa')),
                ('duration', models.DurationField(verbose_name='Duração')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musics.music')),
            ],
        ),
    ]
