# Generated by Django 4.2.7 on 2023-12-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=255)),
                ('developer', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('rating', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='frontend/static/images/games/')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
