# Generated by Django 5.0 on 2023-12-09 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('about', models.TextField(verbose_name='Sobre o Jogo')),
                ('platform', models.CharField(choices=[('PC', 'PC'), ('Playstation 1', 'Playstation 1'), ('Playstation 2', 'Playstation 2'), ('Playstation 3', 'Playstation 3'), ('Playstation 4', 'Playstation 4'), ('Playstation 5', 'Playstation 5'), ('Xbox 360', 'Xbox 360'), ('Xbox One', 'Xbox One'), ('Mega Drive', 'Mega Drive'), ('Super Nintendo', 'Super Nintendo'), ('Nintendo 64', 'Nintendo 64'), ('Game Boy Color', 'Game Boy Color'), ('Game Boy Advance', 'Game Boy Advance'), ('Nintendo Wii', 'Nintendo Wii'), ('Nintendo DS', 'Nintendo DS'), ('Nintendo Switch', 'Nintendo Switch')], max_length=16, verbose_name='Plataforma')),
                ('developer', models.CharField(max_length=255, verbose_name='Desenvolvedor')),
                ('publisher', models.CharField(max_length=255, verbose_name='Distribuidor')),
                ('release_date', models.DateField(verbose_name='Data de lançamento')),
                ('rating', models.IntegerField(verbose_name='Classificação')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('img', models.ImageField(upload_to='frontend/static/upload/games/', verbose_name='Imagem')),
                ('slug', models.SlugField(unique=True)),
                ('categories', models.ManyToManyField(to='games.category', verbose_name='Categorias')),
            ],
        ),
    ]
