# Generated by Django 5.0 on 2023-12-09 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('synopsis', models.TextField(verbose_name='Sinopse')),
                ('directors', models.CharField(max_length=255, verbose_name='Diretores')),
                ('release_date', models.DateField(verbose_name='Data de lançamento')),
                ('running_time', models.IntegerField(verbose_name='Duração')),
                ('rating', models.IntegerField(verbose_name='Classificação')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço')),
                ('img', models.ImageField(upload_to='frontend/static/upload/movies/', verbose_name='Imagem')),
                ('copias', models.IntegerField(verbose_name='Cópias')),
                ('slug', models.SlugField(unique=True)),
                ('categories', models.ManyToManyField(to='movies.category', verbose_name='Categorias')),
            ],
        ),
    ]
