# Generated by Django 4.2.7 on 2023-12-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='img',
            field=models.ImageField(upload_to='frontend/static/images/movies/'),
        ),
    ]
